export enum ChatStatus {
    IDLE = 'IDLE',

    PREPARING = 'PREPARING',
    INITIALIZING_NAMESPACE = 'INITIALIZING_NAMESPACE',
    CLEARING_NAMESPACE = 'CLEARING_NAMESPACE',
    SCRAPING_REPOSITORY = 'SCRAPING_REPOSITORY',
    CHUNKING_FILES = 'CHUNKING_FILES',
    CONTEXTUALIZING_CHUNKS = 'CONTEXTUALIZING_CHUNKS',
    GENERATING_EMBEDDINGS = 'GENERATING_EMBEDDINGS',
    UPSERTING_VECTORS = 'UPSERTING_VECTORS',

    READY = 'READY',

    RECEIVED_MESSAGE = 'RECEIVED_MESSAGE',
    BUILDING_PIPELINE = 'BUILDING_PIPELINE',
    REFINING_QUERY = 'REFINING_QUERY',
    RETRIEVING_DOCUMENTS = 'RETRIEVING_DOCUMENTS',
    RERANKING_DOCUMENTS = 'RERANKING_DOCUMENTS',
    GENERATING_RESPONSE = 'GENERATING_RESPONSE',

    LOADIING = 'LOADING',
    RESPONDING = 'RESPONDING',

    ERROR = 'ERROR',
}
